# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: coodesker.coodesker-desktop
PackageVersion: 1.0.4.1
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.4.1/Coodesker-x64_1.0.4.1.exe
  InstallerSha256: 69699AC1B04B5D4D74485D349F478778910D394010AE189A257C0DDAF7148E6A
ManifestType: installer
ManifestVersion: 1.4.0
